name: yoga_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  provider: ^6.0.3
  badges: ^2.0.3
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  rive: ^0.9.1
  intl: ^0.17.0
  image: ^3.2.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - asset/
    - asset/01_Suryanamskar/
    - asset/logo/
    - asset/yoga/
    - asset/kegels/
    - asset/meditation/
    - asset/food_recommendation/

  fonts:
    - family: Avenir
      fonts:
        - asset: asset/Avenir.ttf
    - family: Ethnocentric
      fonts:
        - asset: asset/Ethnocentric.ttf





























